# Generated by Django 5.0.3 on 2024-05-22 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userwallet',
            name='user',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='UserWallet',
        ),
    ]
