# Generated by Django 5.0.3 on 2024-03-21 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='img',
            field=models.ImageField(default='img', upload_to='media/img'),
        ),
    ]
