# Generated by Django 5.0.3 on 2024-04-01 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(choices=[('new', 'new'), ('featured', 'featured'), ('promo', 'promo'), ('ankara', 'ankara'), ('shoes', 'shoes')], default='', on_delete=django.db.models.deletion.CASCADE, to='store.category'),
        ),
    ]
