# Generated by Django 5.0.3 on 2024-04-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_big_banner',
            field=models.BooleanField(default=False),
        ),
    ]
