# Generated by Django 5.0.3 on 2024-03-21 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_item_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='img',
            field=models.ImageField(default='img', upload_to='static/media/img'),
        ),
    ]
