# Generated by Django 5.0.3 on 2024-04-06 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_is_big_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_big_banner',
        ),
    ]
