# Generated by Django 5.0.3 on 2024-03-24 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_item_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='img',
            new_name='main_img',
        ),
        migrations.RemoveField(
            model_name='item',
            name='color',
        ),
        migrations.AddField(
            model_name='item',
            name='sub_img1',
            field=models.ImageField(default='img', upload_to='static/media/img'),
        ),
        migrations.AddField(
            model_name='item',
            name='sub_img2',
            field=models.ImageField(default='img', upload_to='static/media/img'),
        ),
        migrations.AddField(
            model_name='item',
            name='sub_img3',
            field=models.ImageField(default='img', upload_to='static/media/img'),
        ),
    ]
