# Generated by Django 5.0.3 on 2024-05-13 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_billingaddress_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingaddress',
            name='telephone',
        ),
    ]
