# Generated by Django 5.0.3 on 2024-04-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(choices=[('new', 'new'), ('featured', 'featured'), ('promo', 'promo'), ('ankara', 'ankara'), ('shoes', 'shoes')], max_length=255),
        ),
    ]
