# Generated by Django 5.0.3 on 2024-05-30 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=1000)),
                ('price', models.IntegerField(default=0)),
                ('discount_price', models.IntegerField(default=0)),
                ('img_1', models.ImageField(default='img', upload_to='static/media/img')),
                ('img_2', models.ImageField(default='img', upload_to='static/media/img')),
                ('img_3', models.ImageField(default='img', upload_to='static/media/img')),
                ('img_4', models.ImageField(default='img', upload_to='static/media/img')),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('slug', models.SlugField(default=models.CharField(max_length=255))),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], default='female', max_length=10)),
                ('display_on_home_page', models.BooleanField(default=False)),
                ('is_banner', models.BooleanField(default=False)),
                ('is_best_selling', models.BooleanField(default=False)),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='product_store.categories')),
            ],
        ),
    ]
