# Generated by Django 5.0.3 on 2024-04-28 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('new', 'new'), ('featured', 'featured'), ('promo', 'promo'), ('ankara', 'ankara'), ('shoes', 'shoes')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('is_ordered', models.BooleanField(default=False)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ordered', models.BooleanField(default=False)),
                ('product', models.ManyToManyField(to='ecommerce.cart')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, default='', max_digits=9, null=True)),
                ('img_1', models.ImageField(default='img', upload_to='static/media/img')),
                ('img_2', models.ImageField(default='img', upload_to='static/media/img')),
                ('img_3', models.ImageField(default='img', upload_to='static/media/img')),
                ('img_4', models.ImageField(default='img', upload_to='static/media/img')),
                ('label', models.CharField(blank=True, choices=[('new', 'label-new'), ('out', 'label-out'), ('top', 'label-top')], default='', max_length=255)),
                ('slug', models.SlugField(default=models.CharField(max_length=255))),
                ('gender', models.CharField(choices=[('Male', 'male'), ('Female', 'female')], default='female', max_length=10)),
                ('display_on_home_page', models.BooleanField(default=False)),
                ('is_banner', models.BooleanField(default=False)),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ecommerce.category')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.product'),
        ),
    ]
