# Generated by Django 5.0.3 on 2024-04-28 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_best_selling',
            field=models.BooleanField(default=False),
        ),
    ]
