# Generated by Django 5.0.3 on 2024-06-20 02:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='valid_from',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 20, 2, 10, 51, 485398, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 20, 2, 10, 51, 485398, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='img_2',
            field=models.ImageField(blank=True, default='img', null=True, upload_to='static/media/img'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img_3',
            field=models.ImageField(blank=True, default='img', null=True, upload_to='static/media/img'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img_4',
            field=models.ImageField(blank=True, default='img', null=True, upload_to='static/media/img'),
        ),
    ]
