# Generated by Django 5.0.6 on 2024-06-24 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_store', '0002_remove_cart_session_alter_coupon_valid_from_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customersaddress',
            name='payment_option',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_from',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 24, 17, 18, 0, 78484, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_to',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 6, 24, 17, 18, 0, 78484, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 24, 18, 18, 0, 78484)),
        ),
    ]
