# Generated by Django 5.0.6 on 2024-06-28 23:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_store', '0006_cart_size_alter_coupon_valid_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='add_to_cart',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_from',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 28, 23, 48, 58, 2099, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_to',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 6, 28, 23, 48, 58, 2099, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 29, 0, 48, 58, 2099)),
        ),
    ]
