# Generated by Django 5.0.6 on 2024-07-01 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_store', '0006_abujalocation_size_cart_is_in_cart_cart_size_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingMethod',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_from',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 1, 10, 27, 18, 748705, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_to',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 7, 1, 10, 27, 18, 748705, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='customersaddress',
            name='country',
            field=models.CharField(default='Nigeria', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 1, 11, 27, 18, 748705)),
        ),
    ]
