# Generated by Django 5.0.6 on 2024-07-08 08:40

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_store', '0007_order_session_key_alter_coupon_valid_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='valid_from',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 8, 8, 40, 31, 633072, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_to',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 7, 8, 8, 40, 31, 633072, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 8, 9, 40, 31, 648704)),
        ),
        migrations.CreateModel(
            name='SessionCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('is_ordered', models.BooleanField(default=False)),
                ('size', models.CharField(blank=True, max_length=10, null=True)),
                ('is_in_cart', models.BooleanField(default=False)),
                ('cart_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_store.product')),
            ],
        ),
    ]
