# Generated by Django 5.0.3 on 2024-06-05 10:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_store', '0007_alter_category_title_alter_coupon_valid_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='additional_information',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_from',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 5, 10, 46, 33, 531649, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 5, 10, 46, 33, 531649, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'male'), ('Female', 'female')], default='female', max_length=10, null=True),
        ),
    ]
