# Generated by Django 5.0.6 on 2024-06-28 23:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_store', '0007_product_add_to_cart_alter_coupon_valid_from_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='add_to_cart',
        ),
        migrations.AddField(
            model_name='cart',
            name='is_in_cart',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_from',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 28, 23, 51, 40, 233401, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_to',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 6, 28, 23, 51, 40, 233401, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 29, 0, 51, 40, 249031)),
        ),
    ]
