# Generated by Django 5.0.3 on 2024-06-18 07:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_store', '0008_product_additional_information_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='valid_from',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 18, 7, 56, 52, 933760, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 18, 7, 56, 52, 933760, tzinfo=datetime.timezone.utc)),
        ),
    ]
