# Generated by Django 5.0.3 on 2024-06-18 10:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_store', '0009_alter_coupon_valid_from_alter_coupon_valid_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='valid_from',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 18, 10, 53, 39, 924370, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 18, 10, 53, 39, 924370, tzinfo=datetime.timezone.utc)),
        ),
    ]
