# Generated by Django 5.0.3 on 2024-05-28 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_coupon_order_coupon_payment_order_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='valid_from',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 28, 12, 6, 8, 789832, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 28, 12, 6, 8, 789832, tzinfo=datetime.timezone.utc)),
        ),
    ]
